import { expect, test } from '@playwright/test'

test('renders the localized home page', async ({ page }) => {
  await page.goto('/')
  const vacanciesTable = page.getByRole('table', { name: 'Vacancies table' })

  await expect(page.getByRole('heading', { name: /job-search CRM/i })).toBeVisible()
  await expect(page.getByText('Total applications')).toBeVisible()
  await expect(vacanciesTable.getByRole('cell', { name: 'Northstar Labs' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Next actions' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Vacancies' })).toBeVisible()
  await expect(page.getByLabel('Vacancy status filter')).toBeEnabled()
  await page.getByLabel('Vacancy status filter').selectOption('offer')
  await expect(page.getByLabel('Vacancy status filter')).toHaveValue('offer')
  await expect(vacanciesTable.getByRole('cell', { name: 'Atlas Cloud' })).toBeVisible()
  await expect(vacanciesTable.getByRole('cell', { name: 'Northstar Labs' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Reset filters' }).click()
  await expect(vacanciesTable.getByRole('cell', { name: 'Northstar Labs' })).toBeVisible()
  await page.getByRole('searchbox', { name: 'Search' }).fill('no-matches-expected')
  await expect(page.getByText('No vacancies match the current filters.')).toBeVisible()
  await page.getByRole('button', { name: 'Reset filters' }).click()
  const kanban = page.getByLabel('Kanban by status')
  await expect(page.getByRole('heading', { name: 'Kanban by status' })).toBeVisible()
  await expect(kanban.getByText('Wishlist')).toBeVisible()
  await expect(kanban.getByText('BrightBank')).toBeVisible()
  await page.getByRole('button', { name: 'Details' }).nth(2).click()
  await expect(page.getByLabel('Vacancy details')).toContainText('Atlas Cloud')
  await expect(page.getByLabel('Vacancy details')).toContainText('Offer')
  await expect(page.getByLabel('Vacancy details')).toContainText('125,000–150,000 GBP')
  await expect(page.getByRole('heading', { name: 'Add or edit vacancy' })).toBeVisible()
  await page.getByRole('button', { name: 'New vacancy' }).click()
  await page.getByLabel('Stable ID').fill('vacancy-e2e')
  await page.getByLabel('Company').last().fill('E2E Labs')
  await page.getByLabel('Role').last().fill('Frontend Engineer')
  await page.getByRole('button', { name: 'Save vacancy' }).click()
  await expect(page.getByText('Vacancy saved.')).toBeVisible()
  await expect(vacanciesTable.getByRole('cell', { name: 'E2E Labs' })).toBeVisible()
  await expect(page.getByRole('button', { exact: true, name: 'EN' })).toBeVisible()
  await expect(page.getByRole('button', { exact: true, name: 'RU' })).toBeVisible()
})

test('switches locale between english and russian', async ({ page }) => {
  await page.goto('/')

  await expect(page.getByRole('heading', { name: /job-search CRM/i })).toBeVisible()
  await page.getByRole('button', { exact: true, name: 'RU' }).click()
  await expect(page.getByRole('heading', { name: /CRM для поиска работы/i })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Сбросить фильтры' })).toBeVisible()

  await page.getByRole('button', { exact: true, name: 'EN' }).click()
  await expect(page.getByRole('heading', { name: /job-search CRM/i })).toBeVisible()
})
