import type { Interview } from '../schemas/interviews.schema'
import type { Offer } from '../schemas/offers.schema'
import type { PipelineEvent } from '../schemas/pipeline.schema'
import type { Vacancy } from '../schemas/vacancies.schema'

export const mockVacancies = [
  {
    id: 'vacancy-frontend-platform',
    company: 'Northstar Labs',
    role: 'Senior Frontend Engineer',
    status: 'interviewing',
    priority: 'high',
    format: 'remote',
    source: 'referral',
    location: 'Berlin',
    level: 'senior',
    techStack: ['Vue', 'TypeScript', 'Nuxt'],
    salaryMin: 115000,
    salaryMax: 140000,
    currency: 'EUR',
    matchScore: 91,
    appliedAt: '2026-05-02',
    nextActionAt: '2026-05-21T10:00:00Z',
    createdAt: '2026-05-01T09:00:00Z',
    updatedAt: '2026-05-14T15:30:00Z',
    notes: 'Strong product engineering fit.',
  },
  {
    id: 'vacancy-product-crm',
    company: 'SignalWorks',
    role: 'Product Engineer',
    status: 'screening',
    priority: 'medium',
    format: 'hybrid',
    source: 'linkedin',
    location: 'Amsterdam',
    level: 'middle',
    techStack: ['Vue', 'Node.js', 'PostgreSQL'],
    salaryMin: 90000,
    salaryMax: 115000,
    currency: 'EUR',
    matchScore: 78,
    appliedAt: '2026-05-08',
    nextActionAt: '2026-05-18T13:00:00Z',
    createdAt: '2026-05-07T11:20:00Z',
    updatedAt: '2026-05-11T08:00:00Z',
  },
  {
    id: 'vacancy-design-systems',
    company: 'Atlas Cloud',
    role: 'Design Systems Engineer',
    status: 'offer',
    priority: 'urgent',
    format: 'remote',
    source: 'company_site',
    location: 'London',
    level: 'senior',
    techStack: ['Vue', 'Accessibility', 'Storybook'],
    salaryMin: 125000,
    salaryMax: 150000,
    currency: 'GBP',
    matchScore: 88,
    appliedAt: '2026-04-22',
    nextActionAt: '2026-05-19T09:00:00Z',
    createdAt: '2026-04-20T10:00:00Z',
    updatedAt: '2026-05-15T17:00:00Z',
  },
  {
    id: 'vacancy-legacy-modernization',
    company: 'BrightBank',
    role: 'Frontend Modernization Lead',
    status: 'rejected',
    priority: 'low',
    format: 'onsite',
    source: 'recruiter',
    location: 'Prague',
    level: 'lead',
    techStack: ['Vue', 'Migration', 'Testing'],
    salaryMin: 100000,
    salaryMax: 120000,
    currency: 'EUR',
    matchScore: 64,
    appliedAt: '2026-04-10',
    createdAt: '2026-04-09T07:30:00Z',
    updatedAt: '2026-04-30T16:00:00Z',
  },
] satisfies Vacancy[]

export const mockPipelineEvents = [
  {
    id: 'pipeline-platform-applied',
    vacancyId: 'vacancy-frontend-platform',
    stage: 'applied',
    status: 'completed',
    occurredAt: '2026-05-02T09:00:00Z',
  },
  {
    id: 'pipeline-platform-technical',
    vacancyId: 'vacancy-frontend-platform',
    stage: 'technical_screen',
    status: 'scheduled',
    title: 'Vue architecture interview',
    scheduledAt: '2026-05-21T10:00:00Z',
  },
  {
    id: 'pipeline-crm-screen',
    vacancyId: 'vacancy-product-crm',
    stage: 'recruiter_screen',
    status: 'scheduled',
    scheduledAt: '2026-05-18T13:00:00Z',
  },
  {
    id: 'pipeline-systems-offer',
    vacancyId: 'vacancy-design-systems',
    stage: 'offer',
    status: 'completed',
    completedAt: '2026-05-15T17:00:00Z',
  },
] satisfies PipelineEvent[]

export const mockInterviews = [
  {
    id: 'interview-platform-technical',
    vacancyId: 'vacancy-frontend-platform',
    pipelineEventId: 'pipeline-platform-technical',
    stage: 'technical_screen',
    scheduledAt: '2026-05-21T10:00:00Z',
    result: 'pending',
    interviewerNames: ['Maya', 'Oleg'],
    location: 'Google Meet',
  },
  {
    id: 'interview-crm-recruiter',
    vacancyId: 'vacancy-product-crm',
    pipelineEventId: 'pipeline-crm-screen',
    stage: 'recruiter_screen',
    scheduledAt: '2026-05-18T13:00:00Z',
    result: 'pending',
    interviewerNames: ['Nina'],
    location: 'Zoom',
  },
] satisfies Interview[]

export const mockOffers = [
  {
    id: 'offer-design-systems',
    vacancyId: 'vacancy-design-systems',
    decision: 'pending',
    offeredAt: '2026-05-15T17:00:00Z',
    decisionDueAt: '2026-05-22',
    salaryMin: 130000,
    salaryMax: 145000,
    currency: 'GBP',
  },
] satisfies Offer[]
